version: '3'
services:
  pronto:
    image: ghcr.io/heromo/pronto-action:v1.68.0
    volumes:
      - .:/app
    entrypoint: ["bundle", "exec", "pronto"]
    command: run /app -r eslint_npm

# Run the following command to run pronto locally
# > docker-compose -f docker-compose-pronto.yml run --rm pronto
# > docker-compose -f docker-compose-pronto.yml run --rm pronto run /app -r eslint_npm --staged
