name: 'jest'
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ArtiomTr/jest-coverage-report-action@v2
